Map<String, String> coreAr = {
  'WELCOME': 'Welcome to \nFamily Guard',
  'SIGN_IN': 'Sign in',
  'WITH_PHOE_NUMBER': 'with phone number',
  'OR_WITH_Social_SIGN_IN': 'or with social sign in',
  'PHONE_NUMBER': 'Phone number*',
  'PASSWORD': 'Password*',
  'SHOW_PASSWORD': 'Show password',
  'FORGET_PASSWORD': 'Forget password',
  'NOT_A_MEMEBER_YET': 'Not a member yet',
  'SIGN_UP_NOW': 'Sign up now',
  'SIGN_UP': 'Sign up',
  'FAMILY_NAME': 'Family name*',
  'SELECT_GENDER': 'Select gender',
  'SIGN_UP_T_AND_C_1': 'I agree on',
  'SIGN_UP_T_AND_C_2': 'Terms and Conditions.',
  'HAVE_AN_ACCOUNT': 'Have an account?',
  "CONFIRM_PASSWORD": "Confirm Password*",
  'VERIFY': 'Verify',
  "FIRSTNAME": "First name*",
  "LASTNAME": "Second name*",
  "PASSWORD_CRITERIA": "Password must contains 8 letters and numbers.",
  "OR_WITH_EMAIL": "Or manual sign up",
  "LOGIN_CANCEL": "Couldn't connect to your account",
  "LOGIN_ERROR": "failed to authenticate the account",
  "First_Name_Accept_Letters_Only": "First Name accept letters only",
  "First_Name_Must_Be_At_Least_2_Characters":
      "First name must be at least 2 characters",
  "Please_Enter_First_Name": "Please, enter first name",
  "Second_Name_Accept_Letters_Only": "Second name accept letters only",
  "Second_Name_Must_Be_At_Least_2_Characters":
      "Second name must be at least 2 characters",
  "Please_Enter_Second_Name": "Please, enter Second Name",
  "Family_Name_Accept_Letters_Only": "Family name accept letters only",
  "Family_Name_Must_Be_At_Least_2_Characters":
      "Family name must be at least 2 characters",
  "Please_Enter_Family_Name": "Please, enter Family Name",
  "Mobile_Number_Is_Not_Correct": "Mobile number is not correct",
  "Email_Is_Not_Correct": "E-mail is not correct",
  "Please_Enter_An_Email": "Please, Enter an E-mail",
  "Password_Criteria_Invalid":
      "Incorrect password format, minimum length 8 letters and numbers",
  "Please_Enter_Password": "Please, Enter Password",
  "Password_Doesnt_Match": "Password doesn’t match",
  'MALE': 'Male',
  'FEMALE': 'Female',
  'ENTER_VERIFICATION_CODE_THAT_WE_SENT_YOU_THROUGH_YOUR_EMAIL_OR_MOBILE_NUMBER':
      'A verification code has been sent to your mobile number',
  //verification  screen
  'VERIFICATION': 'Verification',
  'VERIFYING_YOUR_ACCOUNT': 'Verify your account',
  'WE_HAVE_SENT_YOU_A_CODE_TO': 'We have sent to you a code to verify',

  'SUBMIT': 'Submit',
  'REQUEST_NEW_CODE_IN': 'request new code in',
  "DIDN'T_RECIEVE_THE_VERIFICATION_CODE?":
      'Didn\'t receive the verification code?',
  'SECONDS': 'Seconds',
  "DidN'T_RECEIVE_A_CODE?": "Didn’t receive a code?",
  'RESEND': 'Resend',
  'FailedSavingCredentials': 'Failed Saving Credentials',
  'ENTER_OTP_CODE': 'Enter OTP Code',
  "DETECTING_LOCATION": 'Detect Location',
  'SaveYourAddress':
      'To complete your signing up your home address is required. Please, pickup your right home address',
  'ENTER_EMAIL_OR_MOBILE':
      'Please enter the mobile number associated with your account',
  'Sms': 'SMS',
  'WHATSAPP': 'Whatsapp',
  'CREATE_NEW_PASSWORD': 'Create new password',
  'WE’LL_ASK_FOR_THIS_PASSWORD_WHENEVER_YOU_SIGN_IN':
      'We’ll ask for this password whenever you sign in.',
  'SELECT_CHANNEL': 'Select Channel',
  'AlreadyRegisteredMobile': 'This number is Already registered!!!',
  'MAP': 'Map',
  'FAMILY': 'Family',
  'WELCOME_PROFILE': 'Welcome',
  'NOTIFICATIONS': 'Nofitifications',
  'PROFILE': 'Profile',
  'MY_DETAILS': 'My Details',
  'MYADDRESS': 'My Address',
  'PERSONAL': 'Personal',
  'SETTINGS': 'Settings',
  'CHANGE_PASSWORD': 'Change Password',
  'LOG_OUT': 'Log out',
  'CANCEL': 'Cancel',
  'ADD_MEMBER': 'Add a new member',
  'RECEIVED_REQUESTS': 'Received requests',
  'SEMT_REQUESTS': 'Sent Requests',
  'GENDER': 'Gender',
  'FAMILY_NAME_Profile': 'Family Name',
  'LAST_NAME_Profile': 'Second Name',
  'FIRST_NAME_Profile': 'First Name',
  'MOBILE_NUMBER': 'Mobile Number',
  'EMAIL_ADDRESS': 'Email Address',
  'COUNTRY': 'Country',
  'ADMIN_AREA': 'Admin Area',
  'SUB_ADMIN_AREA': 'Sub Admin Area',
  'LOCALITY': 'Locality',
  'SUB_LOCALTY': 'Sub Locality',
  'STREET': 'Street',
  'POSTAL_CODE': 'Postal Code',
  'YOU_ARE': 'You are:',
  'MEMBER_IS': 'The member is:',
  'SEND_REQUEST': 'Send Request',
  'NO_SENT_REQUEST': 'You have not any sent requests',
  'NO_RECEIVED_REQUEST': 'You have not any received requests'
};
