Map<String, String> coreAr = {
  'WELCOME': 'Welcome to \nFamily Guard',
  'SIGN_IN': 'Sign in',
  'WITH_PHOE_NUMBER': 'with phone number',
  'OR_WITH_Social_SIGN_IN': 'or with social sign in',
  'PHONE_NUMBER': 'Phone number*',
  'PASSWORD': 'Password*',
  'SHOW_PASSWORD': 'Show password',
  'FORGET_PASSWORD': 'Forget password',
  'NOT_A_MEMEBER_YET': 'Not a member yet',
  'SIGN_UP_NOW': 'Sign up now',
  'SIGN_UP': 'Sign up',
  'FAMILY_NAME': 'Nickname*',
  'SELECT_GENDER': 'Select gender',
  'SIGN_UP_T_AND_C_1': 'I agree on',
  'SIGN_UP_T_AND_C_2': 'Terms and Conditions.',
  'HAVE_AN_ACCOUNT': 'Have an account?',
  "CONFIRM_PASSWORD": "Confirm Password*",
  'VERIFY': 'Verify',
  "FIRSTNAME": "First name*",
  "LASTNAME": "Last name*",
  "PASSWORD_CRITERIA": "Password must contains 8 letters and numbers.",
  "OR_WITH_EMAIL": "Or manual sign up",
  "LOGIN_CANCEL": "Couldn't connect to your account",
  "LOGIN_ERROR": "failed to authenticate the account",
  "First_Name_Accept_Letters_Only": "First Name accept letters only",
  "First_Name_Must_Be_At_Least_2_Characters":
      "First name must be at least 2 characters",
  "Please_Enter_First_Name": "Please, enter first name",
  "Second_Name_Accept_Letters_Only": "Last name accept letters only",
  "Second_Name_Must_Be_At_Least_2_Characters":
      "Last name must be at least 2 characters",
  "Please_Enter_Second_Name": "Please, enter Last Name",
  "Family_Name_Accept_Letters_Only": "Nickname accept letters only",
  "Family_Name_Must_Be_At_Least_2_Characters":
      "Family name must be at least 2 characters",
  "Please_Enter_Family_Name": "Please, enter Nickname",
  "Mobile_Number_Is_Not_Correct": "Mobile number is not correct",
  "Email_Is_Not_Correct": "E-mail is not correct",
  "Please_Enter_An_Email": "Please, Enter an E-mail",
  "Password_Criteria_Invalid":
      "Incorrect password format, minimum length 8 letters and numbers",
  "Please_Enter_Password": "Please, Enter Password",
  "Password_Doesnt_Match": "Password doesn’t match",
  'MALE': 'Male',
  'FEMALE': 'Female',
  'ENTER_VERIFICATION_CODE_THAT_WE_SENT_YOU_THROUGH_YOUR_EMAIL_OR_MOBILE_NUMBER':
      'A verification code has been sent to your mobile number',
  //verification  screen
  'VERIFICATION': 'Verification',
  'EMERGENCY_VERIFICATION': 'Emergency Verification',
  'VERIFYING_YOUR_ACCOUNT': 'Verify your account',
  'EMERGENCY_INTRO':
      'Family guard app protects yoy and your family members.\nYou can send an emergency calls for you and also your family members.\n A 24/7 emergency dispatcher will be ready to send police to your locaton.\nThe emergency call will be made by your phone number but you will not pay for the call\nTo be able to send emergecies calls you need to verify the caller ID for your number.\n We will send your data to the dispatcher like your full name, home address, mobile number, your current and last location the time your location updated and the type of the emergency you selected from the app.\nYou should to turn on the location service on your device to be able to make an emergency call.\nTo verify your phone number we will send you a 6 digits code and you will receive a call from +141577234000  , add the 6 digits  ',
  'WE_HAVE_SENT_YOU_A_CODE_TO': 'We have sent to you a code to verify',

  'SUBMIT': 'Submit',
  'REQUEST_NEW_CODE_IN': 'request new code in',
  "DIDN'T_RECIEVE_THE_VERIFICATION_CODE?":
      'Didn\'t receive the verification code?',
  'SECONDS': 'Seconds',
  "DidN'T_RECEIVE_A_CODE?": "Didn’t receive a code?",
  'RESEND': 'Resend',
  'FailedSavingCredentials': 'Failed Saving Credentials',
  'ENTER_OTP_CODE': 'Enter OTP Code',
  "DETECTING_LOCATION": 'Detect Location',
  'SaveYourAddress':
      'To complete your signing up your home address is required. Please, pickup your right home address',
  'ENTER_EMAIL_OR_MOBILE':
      'Please enter the mobile number associated with your account',
  'Sms': 'SMS',
  'WHATSAPP': 'Whatsapp',
  'CREATE_NEW_PASSWORD': 'Create new password',
  'WE’LL_ASK_FOR_THIS_PASSWORD_WHENEVER_YOU_SIGN_IN':
      'We’ll ask for this password whenever you sign in.',
  'SELECT_CHANNEL': 'Select Channel',
  'AlreadyRegisteredMobile': 'This number is Already registered!!!',
  'MAP': 'Map',
  'FAMILY': 'Family',
  'WELCOME_PROFILE': 'Welcome',
  'NOTIFICATIONS': 'Notifications',
  'PROFILE': 'Profile',
  'MY_DETAILS': 'My Details',
  'MYADDRESS': 'My Address',
  'PERSONAL': 'Personal',
  'SETTINGS': 'Settings',
  'CHANGE_PASSWORD': 'Change Password',
  'LOG_OUT': 'Log out',
  'CANCEL': 'Cancel',
  'ADD_MEMBER': 'Add a new member',
  'RECEIVED_REQUESTS': 'Received Member Connections',
  'SEMT_REQUESTS': 'Sent Member Connections',
  'GENDER': 'Gender',
  'FAMILY_NAME_Profile': 'Nickname',
  'LAST_NAME_Profile': 'Last Name',
  'FIRST_NAME_Profile': 'First Name',
  'MOBILE_NUMBER': 'Mobile Number',
  'EMAIL_ADDRESS': 'Email Address',
  'COUNTRY': 'Country',
  'ADMIN_AREA': 'Admin Area',
  'SUB_ADMIN_AREA': 'Sub Admin Area',
  'LOCALITY': 'Locality',
  'SUB_LOCALTY': 'Sub Locality',
  'STREET': 'Street',
  'POSTAL_CODE': 'Postal Code',
  'YOU_ARE': 'Connection to member:',
  'MEMBER_IS': 'The member is:',
  'SEND_REQUEST': 'Send Member Connection',
  'NO_SENT_REQUEST': 'You have not any sent members connections',
  'NO_RECEIVED_REQUEST': 'You have not any received members connections',
  'NO_MEMBERS_ADDED': 'No Members Connections Added Yet',
  'INCOMINGCALLMESSAGE':
      'You are receiving a phone call from\n+14157234000\nPlease enter the 6 digits validation code during the call',
  'EMERGENCY_CALLS': 'Emergency Calls',
  'Theif': 'Theif',
  'Accident': 'Accident',
  'Fire': 'Fire',
  'Medical_Emergency': 'Medical Emergency',
  'Walking_Alone': 'Walking Alone',
  'Present_In_Active_Shooting': 'Present In Active Shooting',
  'CALLS_LOG': 'Calls Log',
  'EMERGENCY_CASE': 'Emergency Case',
  'CITY': 'City',
  'STATE': 'State',
  'CALL_STATUS': 'Call Status',
  'DATE': 'Call Date',
  'Duration': 'Call Duration',
  'MEMBER_DETAILS': 'Member Details',
};
