Map<String, String> coreEn = {
  'WELCOME': 'Welcome to Silent Safety',
  'SIGN_IN': 'Sign in',
  'WITH_PHOE_NUMBER': 'with phone number',
  'OR_WITH_Social_SIGN_IN': 'or with social sign in',
  'PHONE_NUMBER': 'Phone number*',
  'PASSWORD': 'Password*',
  'SHOW_PASSWORD': 'Show password',
  'FORGET_PASSWORD': 'Forget password',
  'NOT_A_MEMEBER_YET': 'Not a member yet',
  'SIGN_UP_NOW': 'Sign up now',
  'SIGN_UP': 'Sign up',
  'FAMILY_NAME': 'Family name*',
  'SELECT_GENDER': 'Select gender',
  'SIGN_UP_T_AND_C_1': 'I agree on',
  'SIGN_UP_T_AND_C_2': 'Terms and Conditions.',
  'HAVE_AN_ACCOUNT': 'Have an account?',
  "CONFIRM_PASSWORD": "Confirm Password*",
  'VERIFY': 'Verify',
  "FIRSTNAME": "First name*",
  "LASTNAME": "Second name*",
  "PASSWORD_CRITERIA": "Password must contains 8 letters and numbers.",
  "OR_WITH_EMAIL": "Or manual sign up",
  "LOGIN_CANCEL": "Couldn't connect to your account",
  "LOGIN_ERROR": "failed to authenticate the account",
  "First_Name_Accept_Letters_Only": "First Name accept letters only",
  "First_Name_Must_Be_At_Least_2_Characters":
      "First name must be at least 2 characters",
  "Please_Enter_First_Name": "Please, enter first name",
  "Second_Name_Accept_Letters_Only": "Second name accept letters only",
  "Second_Name_Must_Be_At_Least_2_Characters":
      "Second name must be at least 2 characters",
  "Please_Enter_Second_Name": "Please, enter Second Name",
  "Family_Name_Accept_Letters_Only": "Family name accept letters only",
  "Family_Name_Must_Be_At_Least_2_Characters":
      "Family name must be at least 2 characters",
  "Please_Enter_Family_Name": "Please, enter Family Name",
  "Mobile_Number_Is_Not_Correct": "Mobile number is not correct",
  "Email_Is_Not_Correct": "E-mail is not correct",
  "Please_Enter_An_Email": "Please, Enter an E-mail",
  "Password_Criteria_Invalid":
      "Incorrect password format, minimum length 8 letters and numbers",
  "Please_Enter_Password": "Please, Enter Password",
  "Password_Doesnt_Match": "Password doesn’t match",
};
