name: family_guard
description: Instant Emergency App Protecting Family And Kids

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  email_validator: ^2.0.1

  datetime_picker_formfield: ^2.0.0

  provider: ^6.0.0
  json_annotation: ^4.1.0
  
  http: ^0.13.3
  get_it: ^7.6.0
  equatable: ^2.0.3
  dartz: ^0.10.0
  pull_to_refresh: ^2.0.0
  
  
  image_picker: ^0.8.4
  fluttertoast: ^8.0.8
 

 
  google_fonts: ^4.0.4
 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  internet_connection_checker: ^1.0.0+1
  flutter_native_splash: ^2.2.3+1
 
  get: ^4.6.5
  path_provider: ^2.0.1
  path: ^1.8.3 
  firebase_core: ^2.14.0
 
  connectivity_plus: ^4.0.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  share_plus: ^4.5.3
  location: ^4.4.0
  simple_gradient_text: ^1.2.4
  awesome_bottom_bar: ^1.2.2
  lottie: ^2.3.2
  shimmer: ^2.0.0
  gradient_borders: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^4.6.3
  dropdown_button2: ^2.1.4
  intl_phone_field: ^3.2.0
  intl: ^0.18.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  another_flushbar: ^1.12.30
  firebase_messaging: ^14.6.5
  dio: ^5.2.1+1
 
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  
  arabic_numbers: ^1.0.0
  firebase_dynamic_links: ^5.3.4
  crypto: ^3.0.3
  url_launcher: ^6.1.12
  grouped_list: ^5.1.2
  modal_bottom_sheet: ^3.0.0-pre
  pin_code_fields: ^8.0.1  
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/png/
    - assets/images/svg/

  fonts:
   
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

