name: family_guard
description: Instant Emergency App Protecting Family And Kids

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+9

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  email_validator: ^3.0.0

  datetime_picker_formfield_new: ^2.1.0

  provider: ^6.1.2
  json_annotation: ^4.9.0
  
  http: ^1.2.2
  get_it: ^8.0.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  pull_to_refresh: ^2.0.0
  
  
  image_picker: ^1.1.2

 

 
  google_fonts: ^6.2.1
 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.4.1
  internet_connection_checker: ^3.0.1
  flutter_native_splash: ^2.4.4
 
  get: ^4.6.6
  path_provider: ^2.1.5
  path:
  firebase_core: ^3.9.0
 
  connectivity_plus: ^6.1.1
  flutter_screenutil: ^5.9.3 
  flutter_svg: ^2.0.5
  share_plus: ^10.1.3
  location: ^7.0.1
  simple_gradient_text: ^1.2.4
  awesome_bottom_bar: ^1.2.2
  lottie: ^3.3.0
  shimmer: ^3.0.0
  gradient_borders: ^1.0.0
  flutter_localization: ^0.3.0
  flutter_launcher_icons: ^0.14.2
  firebase_auth: ^5.3.4
  dropdown_button2: ^2.1.4

  intl: ^0.19.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.5
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  another_flushbar: ^1.12.30
  firebase_messaging: ^15.1.6
  dio: ^5.2.1+1
 
  google_sign_in: ^6.2.2
 
  
  arabic_numbers: ^1.0.0
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  grouped_list: ^6.0.0
  modal_bottom_sheet: ^3.0.0
  pin_code_fields: ^8.0.1
  change_app_package_name: ^1.4.0
  intl_phone_field: ^3.2.0
  flutter_local_notifications: ^18.0.1
  badges: ^3.1.2
  permission_handler: ^11.3.1
  flutter_background_service: ^5.1.0
  disable_battery_optimization: ^1.1.1 
  flutter_background_service_android: ^6.3.0
  flutter_onboard: ^2.0.0
  flutter_speed_dial: ^7.0.0 
  flutter_background_service_ios: ^5.0.3
  just_audio: ^0.9.42
  audio_session: ^0.1.23
  webview_flutter: ^4.10.0
  animated_overflow: ^2.0.0
  fluttertoast: ^8.2.10







dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  


flutter_native_splash:
  color: "#ED2647"
  image: assets/images/png/hs_color_logo.png
   #flutter pub run flutter_native_splash:create
    # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    # image: assets/images/png/logo_color_android_twelve.png

    # Splash screen background color.
    #color: "#1D366F"

    # App icon background color.
    #icon_background_color: "#111111"

    # The image_dark parameter and icon_background_color_dark set the image and icon background
    # color when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"
    image: assets/images/png/hs_color_logo.png

  android: true
  android12: true
  ios: true
  web: true



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/png/
    - assets/images/svg/

  fonts:
   
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: Balsamiq-Sans-Regular
      fonts:
        - asset: assets/fonts/Balsamiq-Sans-Regular.ttf

    - family: Odibee-Sans-Regular
      fonts:
        - asset: assets/fonts/Odibee-Sans-Regular.ttf       
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

